INDIA_STATES = {
    "andhra pradesh",
    "arunachal pradesh",
    "assam",
    "bihar",
    "chhattisgarh",
    "goa",
    "gujarat",
    "haryana",
    "himachal pradesh",
    "jharkhand",
    "karnataka",
    "kerala",
    "madhya pradesh",
    "maharashtra",
    "manipur",
    "meghalaya",
    "mizoram",
    "nagaland",
    "odisha",
    "punjab",
    "rajasthan",
    "sikkim",
    "tamil nadu",
    "telangana",
    "tripura",
    "uttar pradesh",
    "uttarakhand",
    "west bengal",
    "jammu and kashmir",
    "ladakh",
    "delhi",
    "chandigarh",
    "andaman and nicobar islands",
    "dadra and nagar haveli and daman and diu",
    "lakshadweep",
    "puducherry",
}

DISTRICT_TO_STATE = {
    "nagpur": "maharashtra",
    "pune": "maharashtra",
    "mumbai": "maharashtra",
    "thane": "maharashtra",
    "nashik": "maharashtra",
    "chandrapur": "maharashtra",
    "gadchiroli": "maharashtra",
    "delhi": "delhi",
    "new delhi": "delhi",
    "gurugram": "haryana",
    "noida": "uttar pradesh",
    "lucknow": "uttar pradesh",
    "agra": "uttar pradesh",
    "kanpur": "uttar pradesh",
    "varanasi": "uttar pradesh",
    "jaipur": "rajasthan",
    "udaipur": "rajasthan",
    "jodhpur": "rajasthan",
    "kota": "rajasthan",
    "bengaluru": "karnataka",
    "bangalore": "karnataka",
    "mysuru": "karnataka",
    "udupi": "karnataka",
    "mangaluru": "karnataka",
    "shivamogga": "karnataka",
    "chennai": "tamil nadu",
    "coimbatore": "tamil nadu",
    "madurai": "tamil nadu",
    "salem": "tamil nadu",
    "hyderabad": "telangana",
    "warangal": "telangana",
    "khammam": "telangana",
    "visakhapatnam": "andhra pradesh",
    "vijayawada": "andhra pradesh",
    "guntur": "andhra pradesh",
    "kochi": "kerala",
    "thiruvananthapuram": "kerala",
    "kozhikode": "kerala",
    "wayanad": "kerala",
    "palakkad": "kerala",
    "kolkata": "west bengal",
    "darjeeling": "west bengal",
    "jalpaiguri": "west bengal",
    "sundarbans": "west bengal",
    "guwahati": "assam",
    "kaziranga": "assam",
    "jorhat": "assam",
    "dibrugarh": "assam",
    "bhubaneswar": "odisha",
    "cuttack": "odisha",
    "koraput": "odisha",
    "similipal": "odisha",
    "ranchi": "jharkhand",
    "jamshedpur": "jharkhand",
    "dhanbad": "jharkhand",
    "patna": "bihar",
    "gaya": "bihar",
    "bhagalpur": "bihar",
    "raipur": "chhattisgarh",
    "bilaspur": "chhattisgarh",
    "jagdalpur": "chhattisgarh",
    "kanha": "madhya pradesh",
    "bhopal": "madhya pradesh",
    "indore": "madhya pradesh",
    "jabalpur": "madhya pradesh",
    "dehradun": "uttarakhand",
    "nainital": "uttarakhand",
    "haridwar": "uttarakhand",
    "corbett": "uttarakhand",
    "srinagar": "jammu and kashmir",
    "jammu": "jammu and kashmir",
    "leh": "ladakh",
    "gir": "gujarat",
    "ahmedabad": "gujarat",
    "surat": "gujarat",
    "vadodara": "gujarat",
    # Additional wildlife hotspots and cities
    "bandipur": "karnataka",
    "nagarhole": "karnataka",
    "bhadra": "karnataka",
    "dandeli": "karnataka",
    "hubli": "karnataka",
    "dharwad": "karnataka",
    "bellary": "karnataka",
    "raichur": "karnataka",
    "kodagu": "karnataka",
    "periyar": "kerala",
    "thekkady": "kerala",
    "munnar": "kerala",
    "idukki": "kerala",
    "kannur": "kerala",
    "malappuram": "kerala",
    "ernakulam": "kerala",
    "nilgiri": "tamil nadu",
    "mudumalai": "tamil nadu",
    "ooty": "tamil nadu",
    "tirunelveli": "tamil nadu",
    "thanjavur": "tamil nadu",
    "rameswaram": "tamil nadu",
    "trichy": "tamil nadu",
    "satpura": "madhya pradesh",
    "panna": "madhya pradesh",
    "pench": "madhya pradesh",
    "bandhavgarh": "madhya pradesh",
    "gwalior": "madhya pradesh",
    "ujjain": "madhya pradesh",
    "sagar": "madhya pradesh",
    "ranthambore": "rajasthan",
    "sariska": "rajasthan",
    "alwar": "rajasthan",
    "bharatpur": "rajasthan",
    "keoladeo": "rajasthan",
    "sawai madhopur": "rajasthan",
    "rajaji": "uttarakhand",
    "rishikesh": "uttarakhand",
    "mussoorie": "uttarakhand",
    "almora": "uttarakhand",
    "sundarbans": "west bengal",
    "siliguri": "west bengal",
    "howrah": "west bengal",
    "manas": "assam",
    "tezpur": "assam",
    "silchar": "assam",
    "nameri": "assam",
    "imphal": "manipur",
    "kohima": "nagaland",
    "agartala": "tripura",
    "aizawl": "mizoram",
    "shillong": "meghalaya",
    "itanagar": "arunachal pradesh",
    "namdapha": "arunachal pradesh",
    "gangtok": "sikkim",
    "kanchenjunga": "sikkim",
    "panna": "madhya pradesh",
    "tadoba": "maharashtra",
    "melghat": "maharashtra",
    "sanjay gandhi": "maharashtra",
    "kolhapur": "maharashtra",
    "aurangabad": "maharashtra",
    "solapur": "maharashtra",
    "satara": "maharashtra",
    "ratnagiri": "maharashtra",
    "gondia": "maharashtra",
    "valmiki": "bihar",
    "betla": "jharkhand",
    "hazaribagh": "jharkhand",
    "achanakmar": "chhattisgarh",
    "indravati": "chhattisgarh",
    "barnawapara": "chhattisgarh",
    "chandigarh": "chandigarh",
    "amritsar": "punjab",
    "ludhiana": "punjab",
    "harike": "punjab",
    "port blair": "andaman and nicobar islands",
    "panaji": "goa",
    "margao": "goa",
    "tirupati": "andhra pradesh",
    "nellore": "andhra pradesh",
    "anantapur": "andhra pradesh",
    "kakinada": "andhra pradesh",
    "karimnagar": "telangana",
    "nizamabad": "telangana",
    "adilabad": "telangana",
    "nagarjuna sagar": "telangana",
    # Hindi / Devanagari script city names
    "मुंबई": "maharashtra",
    "दिल्ली": "delhi",
    "बेंगलुरु": "karnataka",
    "कोलकाता": "west bengal",
    "चेन्नई": "tamil nadu",
    "हैदराबाद": "telangana",
    "लखनऊ": "uttar pradesh",
    "जयपुर": "rajasthan",
    "भोपाल": "madhya pradesh",
    "पटना": "bihar",
    "गुवाहाटी": "assam",
    "नागपुर": "maharashtra",
    "पुणे": "maharashtra",
    "कोल्हापुर": "maharashtra",
    "जगदलपुर": "chhattisgarh",
    "रायपुर": "chhattisgarh",
    "रांची": "jharkhand",
    "भुवनेश्वर": "odisha",
    "देहरादून": "uttarakhand",
    "शिमला": "himachal pradesh",
    "इंदौर": "madhya pradesh",
    "जबलपुर": "madhya pradesh",
    "अहमदाबाद": "gujarat",
    "सूरत": "gujarat",
    "चंडीगढ़": "chandigarh",
    "अमृतसर": "punjab",
    "श्रीनगर": "jammu and kashmir",
    "इम्फाल": "manipur",
    "कोहिमा": "nagaland",
    "अगरतला": "tripura",
    "शिलांग": "meghalaya",
    "गंगटोक": "sikkim",
    # Kannada script city names
    "ಬೆಂಗಳೂರು": "karnataka",
    "ಮೈಸೂರು": "karnataka",
    "ಮಂಗಳೂರು": "karnataka",
    "ಹುಬ್ಬಳ್ಳಿ": "karnataka",
    "ಬಳ್ಳಾರಿ": "karnataka",
    "ಶಿವಮೊಗ್ಗ": "karnataka",
    "ಬಂಡೀಪುರ": "karnataka",
    "ನಾಗರಹೊಳೆ": "karnataka",
    # Tamil script city names
    "சென்னை": "tamil nadu",
    "கோயம்புத்தூர்": "tamil nadu",
    "மதுரை": "tamil nadu",
    # Telugu script city names
    "హైదరాబాద్": "telangana",
    "విశాఖపట్నం": "andhra pradesh",
    "విజయవాడ": "andhra pradesh",
    # Bengali script city names
    "কলকাতা": "west bengal",
    "দার্জিলিং": "west bengal",
    # Malayalam script city names
    "കൊച്ചി": "kerala",
    "തിരുവനന്തപുരം": "kerala",
    # Marathi script city names
    "मुंबई": "maharashtra",
    "पुणे": "maharashtra",
    "नागपूर": "maharashtra",
    "कोल्हापूर": "maharashtra",
    # Gujarati script city names
    "અમદાવાદ": "gujarat",
    "સુરત": "gujarat",
    # Punjabi script city names
    "ਅੰਮ੍ਰਿਤਸਰ": "punjab",
    "ਲੁਧਿਆਣਾ": "punjab",
    "ਚੰਡੀਗੜ੍ਹ": "chandigarh",
    "ਪੰਜਾਬ": "punjab",
}
