INDIA_STATES = {
    "andhra pradesh",
    "arunachal pradesh",
    "assam",
    "bihar",
    "chhattisgarh",
    "goa",
    "gujarat",
    "haryana",
    "himachal pradesh",
    "jharkhand",
    "karnataka",
    "kerala",
    "madhya pradesh",
    "maharashtra",
    "manipur",
    "meghalaya",
    "mizoram",
    "nagaland",
    "odisha",
    "punjab",
    "rajasthan",
    "sikkim",
    "tamil nadu",
    "telangana",
    "tripura",
    "uttar pradesh",
    "uttarakhand",
    "west bengal",
    "jammu and kashmir",
    "ladakh",
    "delhi",
    "chandigarh",
    "andaman and nicobar islands",
    "dadra and nagar haveli and daman and diu",
    "lakshadweep",
    "puducherry",
}

DISTRICT_TO_STATE = {
    "nagpur": "maharashtra",
    "pune": "maharashtra",
    "mumbai": "maharashtra",
    "thane": "maharashtra",
    "nashik": "maharashtra",
    "chandrapur": "maharashtra",
    "gadchiroli": "maharashtra",
    "delhi": "delhi",
    "new delhi": "delhi",
    "gurugram": "haryana",
    "noida": "uttar pradesh",
    "lucknow": "uttar pradesh",
    "agra": "uttar pradesh",
    "kanpur": "uttar pradesh",
    "varanasi": "uttar pradesh",
    "jaipur": "rajasthan",
    "udaipur": "rajasthan",
    "jodhpur": "rajasthan",
    "kota": "rajasthan",
    "bengaluru": "karnataka",
    "bangalore": "karnataka",
    "mysuru": "karnataka",
    "udupi": "karnataka",
    "mangaluru": "karnataka",
    "shivamogga": "karnataka",
    "chennai": "tamil nadu",
    "coimbatore": "tamil nadu",
    "madurai": "tamil nadu",
    "salem": "tamil nadu",
    "hyderabad": "telangana",
    "warangal": "telangana",
    "khammam": "telangana",
    "visakhapatnam": "andhra pradesh",
    "vijayawada": "andhra pradesh",
    "guntur": "andhra pradesh",
    "kochi": "kerala",
    "thiruvananthapuram": "kerala",
    "kozhikode": "kerala",
    "wayanad": "kerala",
    "palakkad": "kerala",
    "kolkata": "west bengal",
    "darjeeling": "west bengal",
    "jalpaiguri": "west bengal",
    "sundarbans": "west bengal",
    "guwahati": "assam",
    "kaziranga": "assam",
    "jorhat": "assam",
    "dibrugarh": "assam",
    "bhubaneswar": "odisha",
    "cuttack": "odisha",
    "koraput": "odisha",
    "similipal": "odisha",
    "ranchi": "jharkhand",
    "jamshedpur": "jharkhand",
    "dhanbad": "jharkhand",
    "patna": "bihar",
    "gaya": "bihar",
    "bhagalpur": "bihar",
    "raipur": "chhattisgarh",
    "bilaspur": "chhattisgarh",
    "jagdalpur": "chhattisgarh",
    "kanha": "madhya pradesh",
    "bhopal": "madhya pradesh",
    "indore": "madhya pradesh",
    "jabalpur": "madhya pradesh",
    "dehradun": "uttarakhand",
    "nainital": "uttarakhand",
    "haridwar": "uttarakhand",
    "corbett": "uttarakhand",
    "srinagar": "jammu and kashmir",
    "jammu": "jammu and kashmir",
    "leh": "ladakh",
    "gir": "gujarat",
    "ahmedabad": "gujarat",
    "surat": "gujarat",
    "vadodara": "gujarat",
}
