INDIA_STATES = {
    "andhra pradesh", "arunachal pradesh", "assam", "bihar", "chhattisgarh",
    "goa", "gujarat", "haryana", "himachal pradesh", "jharkhand", "karnataka",
    "kerala", "madhya pradesh", "maharashtra", "manipur", "meghalaya",
    "mizoram", "nagaland", "odisha", "punjab", "rajasthan", "sikkim",
    "tamil nadu", "telangana", "tripura", "uttar pradesh", "uttarakhand",
    "west bengal", "jammu and kashmir", "ladakh", "delhi", "chandigarh",
    "andaman and nicobar islands", "dadra and nagar haveli and daman and diu",
    "lakshadweep", "puducherry",
}

DISTRICT_TO_STATE = {
    "visakhapatnam": "andhra pradesh",
    "vijayawada": "andhra pradesh",
    "guntur": "andhra pradesh",
    "tirupati": "andhra pradesh",
    "nellore": "andhra pradesh",
    "kakinada": "andhra pradesh",
    "kadapa": "andhra pradesh",
    "anantapur": "andhra pradesh",
    "kurnool": "andhra pradesh",
    "rajahmundry": "andhra pradesh",
    "eluru": "andhra pradesh",
    "ongole": "andhra pradesh",
    "srikakulam": "andhra pradesh",
    "vizianagaram": "andhra pradesh",
    "chittoor": "andhra pradesh",
    "prakasam": "andhra pradesh",
    "east godavari": "andhra pradesh",
    "west godavari": "andhra pradesh",
    "krishna": "andhra pradesh",
    "nandyal": "andhra pradesh",
    "machilipatnam": "andhra pradesh",
    "narasaraopet": "andhra pradesh",
    "seshachalam": "andhra pradesh",
    "sri venkateswara": "andhra pradesh",
    "itanagar": "arunachal pradesh",
    "namdapha": "arunachal pradesh",
    "tawang": "arunachal pradesh",
    "ziro": "arunachal pradesh",
    "pasighat": "arunachal pradesh",
    "bomdila": "arunachal pradesh",
    "along": "arunachal pradesh",
    "tezu": "arunachal pradesh",
    "changlang": "arunachal pradesh",
    "dibang valley": "arunachal pradesh",
    "pakke": "arunachal pradesh",
    "mouling": "arunachal pradesh",
    "guwahati": "assam",
    "kaziranga": "assam",
    "jorhat": "assam",
    "dibrugarh": "assam",
    "manas": "assam",
    "tezpur": "assam",
    "silchar": "assam",
    "nameri": "assam",
    "nagaon": "assam",
    "tinsukia": "assam",
    "goalpara": "assam",
    "bongaigaon": "assam",
    "kamrup": "assam",
    "cachar": "assam",
    "barpeta": "assam",
    "karimganj": "assam",
    "nalbari": "assam",
    "sonitpur": "assam",
    "lakhimpur": "assam",
    "dhubri": "assam",
    "pobitora": "assam",
    "orang": "assam",
    "dibru saikhowa": "assam",
    "patna": "bihar",
    "gaya": "bihar",
    "bhagalpur": "bihar",
    "valmiki": "bihar",
    "muzaffarpur": "bihar",
    "darbhanga": "bihar",
    "purnia": "bihar",
    "begusarai": "bihar",
    "nalanda": "bihar",
    "saharsa": "bihar",
    "araria": "bihar",
    "katihar": "bihar",
    "madhubani": "bihar",
    "saran": "bihar",
    "vaishali": "bihar",
    "champaran": "bihar",
    "east champaran": "bihar",
    "west champaran": "bihar",
    "nawada": "bihar",
    "raipur": "chhattisgarh",
    "bilaspur": "chhattisgarh",
    "jagdalpur": "chhattisgarh",
    "achanakmar": "chhattisgarh",
    "indravati": "chhattisgarh",
    "barnawapara": "chhattisgarh",
    "durg": "chhattisgarh",
    "korba": "chhattisgarh",
    "rajnandgaon": "chhattisgarh",
    "bastar": "chhattisgarh",
    "surguja": "chhattisgarh",
    "dhamtari": "chhattisgarh",
    "jashpur": "chhattisgarh",
    "koriya": "chhattisgarh",
    "kanker": "chhattisgarh",
    "mahasamund": "chhattisgarh",
    "udanti sitanadi": "chhattisgarh",
    "guru ghasidas": "chhattisgarh",
    "delhi": "delhi",
    "new delhi": "delhi",
    "panaji": "goa",
    "margao": "goa",
    "vasco": "goa",
    "mapusa": "goa",
    "ponda": "goa",
    "north goa": "goa",
    "south goa": "goa",
    "bhagwan mahavir": "goa",
    "mollem": "goa",
    "gir": "gujarat",
    "ahmedabad": "gujarat",
    "surat": "gujarat",
    "vadodara": "gujarat",
    "rajkot": "gujarat",
    "bhavnagar": "gujarat",
    "jamnagar": "gujarat",
    "junagadh": "gujarat",
    "gandhinagar": "gujarat",
    "kutch": "gujarat",
    "bhuj": "gujarat",
    "anand": "gujarat",
    "bharuch": "gujarat",
    "mehsana": "gujarat",
    "patan": "gujarat",
    "porbandar": "gujarat",
    "narmada": "gujarat",
    "velavadar": "gujarat",
    "marine national park": "gujarat",
    "wild ass sanctuary": "gujarat",
    "dindoli": "gujarat",
    "gurugram": "haryana",
    "faridabad": "haryana",
    "panipat": "haryana",
    "ambala": "haryana",
    "karnal": "haryana",
    "hisar": "haryana",
    "rohtak": "haryana",
    "sonipat": "haryana",
    "yamunanagar": "haryana",
    "panchkula": "haryana",
    "sultanpur": "haryana",
    "kalesar": "haryana",
    "bhindawas": "haryana",
    "shimla": "himachal pradesh",
    "manali": "himachal pradesh",
    "dharamshala": "himachal pradesh",
    "kullu": "himachal pradesh",
    "kangra": "himachal pradesh",
    "mandi": "himachal pradesh",
    "solan": "himachal pradesh",
    "sirmaur": "himachal pradesh",
    "hamirpur": "himachal pradesh",
    "una": "himachal pradesh",
    "kinnaur": "himachal pradesh",
    "lahaul": "himachal pradesh",
    "spiti": "himachal pradesh",
    "chamba": "himachal pradesh",
    "great himalayan": "himachal pradesh",
    "pin valley": "himachal pradesh",
    "ranchi": "jharkhand",
    "jamshedpur": "jharkhand",
    "dhanbad": "jharkhand",
    "betla": "jharkhand",
    "hazaribagh": "jharkhand",
    "bokaro": "jharkhand",
    "deoghar": "jharkhand",
    "dumka": "jharkhand",
    "giridih": "jharkhand",
    "palamu": "jharkhand",
    "gumla": "jharkhand",
    "latehar": "jharkhand",
    "chatra": "jharkhand",
    "east singhbhum": "jharkhand",
    "west singhbhum": "jharkhand",
    "dalma": "jharkhand",
    "bengaluru": "karnataka",
    "bangalore": "karnataka",
    "mysuru": "karnataka",
    "mysore": "karnataka",
    "udupi": "karnataka",
    "mangaluru": "karnataka",
    "mangalore": "karnataka",
    "shivamogga": "karnataka",
    "shimoga": "karnataka",
    "bandipur": "karnataka",
    "nagarhole": "karnataka",
    "bhadra": "karnataka",
    "dandeli": "karnataka",
    "hubli": "karnataka",
    "dharwad": "karnataka",
    "bellary": "karnataka",
    "ballari": "karnataka",
    "raichur": "karnataka",
    "kodagu": "karnataka",
    "coorg": "karnataka",
    "belgaum": "karnataka",
    "belagavi": "karnataka",
    "gulbarga": "karnataka",
    "kalaburagi": "karnataka",
    "tumkur": "karnataka",
    "tumakuru": "karnataka",
    "davangere": "karnataka",
    "hassan": "karnataka",
    "mandya": "karnataka",
    "chamarajanagar": "karnataka",
    "chikmagalur": "karnataka",
    "bidar": "karnataka",
    "gadag": "karnataka",
    "koppal": "karnataka",
    "yadgir": "karnataka",
    "bagalkot": "karnataka",
    "uttara kannada": "karnataka",
    "dakshina kannada": "karnataka",
    "haveri": "karnataka",
    "chitradurga": "karnataka",
    "ranganathittu": "karnataka",
    "biligiri": "karnataka",
    "br hills": "karnataka",
    "kabini": "karnataka",
    "anshi": "karnataka",
    "kochi": "kerala",
    "thiruvananthapuram": "kerala",
    "kozhikode": "kerala",
    "wayanad": "kerala",
    "palakkad": "kerala",
    "periyar": "kerala",
    "thekkady": "kerala",
    "munnar": "kerala",
    "idukki": "kerala",
    "kannur": "kerala",
    "malappuram": "kerala",
    "ernakulam": "kerala",
    "thrissur": "kerala",
    "kollam": "kerala",
    "alappuzha": "kerala",
    "kottayam": "kerala",
    "pathanamthitta": "kerala",
    "kasaragod": "kerala",
    "silent valley": "kerala",
    "eravikulam": "kerala",
    "parambikulam": "kerala",
    "chinnar": "kerala",
    "kanha": "madhya pradesh",
    "bhopal": "madhya pradesh",
    "indore": "madhya pradesh",
    "jabalpur": "madhya pradesh",
    "satpura": "madhya pradesh",
    "panna": "madhya pradesh",
    "pench": "madhya pradesh",
    "bandhavgarh": "madhya pradesh",
    "gwalior": "madhya pradesh",
    "ujjain": "madhya pradesh",
    "sagar": "madhya pradesh",
    "rewa": "madhya pradesh",
    "satna": "madhya pradesh",
    "chhindwara": "madhya pradesh",
    "hoshangabad": "madhya pradesh",
    "betul": "madhya pradesh",
    "seoni": "madhya pradesh",
    "mandla": "madhya pradesh",
    "dindori": "madhya pradesh",
    "balaghat": "madhya pradesh",
    "shivpuri": "madhya pradesh",
    "morena": "madhya pradesh",
    "tikamgarh": "madhya pradesh",
    "damoh": "madhya pradesh",
    "dewas": "madhya pradesh",
    "ratapani": "madhya pradesh",
    "nagpur": "maharashtra",
    "pune": "maharashtra",
    "mumbai": "maharashtra",
    "thane": "maharashtra",
    "nashik": "maharashtra",
    "chandrapur": "maharashtra",
    "gadchiroli": "maharashtra",
    "tadoba": "maharashtra",
    "melghat": "maharashtra",
    "sanjay gandhi": "maharashtra",
    "kolhapur": "maharashtra",
    "aurangabad": "maharashtra",
    "solapur": "maharashtra",
    "satara": "maharashtra",
    "ratnagiri": "maharashtra",
    "gondia": "maharashtra",
    "amravati": "maharashtra",
    "wardha": "maharashtra",
    "yavatmal": "maharashtra",
    "sangli": "maharashtra",
    "ahmednagar": "maharashtra",
    "jalgaon": "maharashtra",
    "dhule": "maharashtra",
    "nanded": "maharashtra",
    "latur": "maharashtra",
    "osmanabad": "maharashtra",
    "beed": "maharashtra",
    "parbhani": "maharashtra",
    "hingoli": "maharashtra",
    "washim": "maharashtra",
    "buldhana": "maharashtra",
    "akola": "maharashtra",
    "sindhudurg": "maharashtra",
    "raigad": "maharashtra",
    "palghar": "maharashtra",
    "bhandara": "maharashtra",
    "navi mumbai": "maharashtra",
    "sahyadri": "maharashtra",
    "navegaon": "maharashtra",
    "tipeshwar": "maharashtra",
    "imphal": "manipur",
    "churachandpur": "manipur",
    "thoubal": "manipur",
    "bishnupur": "manipur",
    "keibul lamjao": "manipur",
    "shillong": "meghalaya",
    "tura": "meghalaya",
    "jaintia hills": "meghalaya",
    "east khasi hills": "meghalaya",
    "nokrek": "meghalaya",
    "balpakram": "meghalaya",
    "aizawl": "mizoram",
    "lunglei": "mizoram",
    "champhai": "mizoram",
    "dampa": "mizoram",
    "murlen": "mizoram",
    "kohima": "nagaland",
    "dimapur": "nagaland",
    "mokokchung": "nagaland",
    "intanki": "nagaland",
    "bhubaneswar": "odisha",
    "cuttack": "odisha",
    "koraput": "odisha",
    "similipal": "odisha",
    "baripada": "odisha",
    "nabarangpur": "odisha",
    "puri": "odisha",
    "berhampur": "odisha",
    "sambalpur": "odisha",
    "rourkela": "odisha",
    "balasore": "odisha",
    "mayurbhanj": "odisha",
    "ganjam": "odisha",
    "kalahandi": "odisha",
    "sundargarh": "odisha",
    "angul": "odisha",
    "dhenkanal": "odisha",
    "nayagarh": "odisha",
    "kendrapara": "odisha",
    "bhitarkanika": "odisha",
    "satkosia": "odisha",
    "chandaka": "odisha",
    "chilika": "odisha",
    "debrigarh": "odisha",
    "amritsar": "punjab",
    "ludhiana": "punjab",
    "harike": "punjab",
    "chandigarh": "chandigarh",
    "jalandhar": "punjab",
    "patiala": "punjab",
    "bathinda": "punjab",
    "mohali": "punjab",
    "pathankot": "punjab",
    "hoshiarpur": "punjab",
    "moga": "punjab",
    "firozpur": "punjab",
    "fazilka": "punjab",
    "sangrur": "punjab",
    "barnala": "punjab",
    "jaipur": "rajasthan",
    "udaipur": "rajasthan",
    "jodhpur": "rajasthan",
    "kota": "rajasthan",
    "ranthambore": "rajasthan",
    "sariska": "rajasthan",
    "alwar": "rajasthan",
    "bharatpur": "rajasthan",
    "keoladeo": "rajasthan",
    "sawai madhopur": "rajasthan",
    "bikaner": "rajasthan",
    "ajmer": "rajasthan",
    "jaisalmer": "rajasthan",
    "mount abu": "rajasthan",
    "sikar": "rajasthan",
    "tonk": "rajasthan",
    "bhilwara": "rajasthan",
    "pali": "rajasthan",
    "barmer": "rajasthan",
    "nagaur": "rajasthan",
    "churu": "rajasthan",
    "jhunjhunu": "rajasthan",
    "bundi": "rajasthan",
    "chittorgarh": "rajasthan",
    "dungarpur": "rajasthan",
    "banswara": "rajasthan",
    "pratapgarh": "rajasthan",
    "desert national park": "rajasthan",
    "mukundra": "rajasthan",
    "tal chhapar": "rajasthan",
    "gangtok": "sikkim",
    "kanchenjunga": "sikkim",
    "namchi": "sikkim",
    "pelling": "sikkim",
    "khangchendzonga": "sikkim",
    "chennai": "tamil nadu",
    "coimbatore": "tamil nadu",
    "madurai": "tamil nadu",
    "salem": "tamil nadu",
    "nilgiri": "tamil nadu",
    "mudumalai": "tamil nadu",
    "ooty": "tamil nadu",
    "tirunelveli": "tamil nadu",
    "thanjavur": "tamil nadu",
    "rameswaram": "tamil nadu",
    "trichy": "tamil nadu",
    "tiruchirappalli": "tamil nadu",
    "vellore": "tamil nadu",
    "erode": "tamil nadu",
    "tirupur": "tamil nadu",
    "dindigul": "tamil nadu",
    "kanyakumari": "tamil nadu",
    "thoothukudi": "tamil nadu",
    "tuticorin": "tamil nadu",
    "sivaganga": "tamil nadu",
    "ramanathapuram": "tamil nadu",
    "virudhunagar": "tamil nadu",
    "theni": "tamil nadu",
    "karur": "tamil nadu",
    "namakkal": "tamil nadu",
    "dharmapuri": "tamil nadu",
    "krishnagiri": "tamil nadu",
    "anamalai": "tamil nadu",
    "sathyamangalam": "tamil nadu",
    "kalakkad mundanthurai": "tamil nadu",
    "guindy": "tamil nadu",
    "vedanthangal": "tamil nadu",
    "gulf of mannar": "tamil nadu",
    "point calimere": "tamil nadu",
    "hyderabad": "telangana",
    "warangal": "telangana",
    "khammam": "telangana",
    "karimnagar": "telangana",
    "nizamabad": "telangana",
    "adilabad": "telangana",
    "nagarjuna sagar": "telangana",
    "makthal": "telangana",
    "shadnagar": "telangana",
    "nalgonda": "telangana",
    "medak": "telangana",
    "rangareddy": "telangana",
    "secunderabad": "telangana",
    "mahbubnagar": "telangana",
    "sangareddy": "telangana",
    "siddipet": "telangana",
    "mancherial": "telangana",
    "nirmal": "telangana",
    "kamareddy": "telangana",
    "nagarjunsagar": "telangana",
    "amrabad": "telangana",
    "kawal": "telangana",
    "nampally": "telangana",
    "agartala": "tripura",
    "dharmanagar": "tripura",
    "sepahijala": "tripura",
    "clouded leopard": "tripura",
    "noida": "uttar pradesh",
    "lucknow": "uttar pradesh",
    "agra": "uttar pradesh",
    "kanpur": "uttar pradesh",
    "varanasi": "uttar pradesh",
    "allahabad": "uttar pradesh",
    "prayagraj": "uttar pradesh",
    "meerut": "uttar pradesh",
    "ghaziabad": "uttar pradesh",
    "bareilly": "uttar pradesh",
    "aligarh": "uttar pradesh",
    "moradabad": "uttar pradesh",
    "saharanpur": "uttar pradesh",
    "gorakhpur": "uttar pradesh",
    "jhansi": "uttar pradesh",
    "mathura": "uttar pradesh",
    "ayodhya": "uttar pradesh",
    "faizabad": "uttar pradesh",
    "rae bareli": "uttar pradesh",
    "unnao": "uttar pradesh",
    "sitapur": "uttar pradesh",
    "hardoi": "uttar pradesh",
    "lakhimpur kheri": "uttar pradesh",
    "shahjahanpur": "uttar pradesh",
    "pilibhit": "uttar pradesh",
    "budaun": "uttar pradesh",
    "etawah": "uttar pradesh",
    "mainpuri": "uttar pradesh",
    "firozabad": "uttar pradesh",
    "dudhwa": "uttar pradesh",
    "katarniaghat": "uttar pradesh",
    "chambal": "uttar pradesh",
    "national chambal": "uttar pradesh",
    "dehradun": "uttarakhand",
    "nainital": "uttarakhand",
    "haridwar": "uttarakhand",
    "corbett": "uttarakhand",
    "rajaji": "uttarakhand",
    "rishikesh": "uttarakhand",
    "mussoorie": "uttarakhand",
    "almora": "uttarakhand",
    "pithoragarh": "uttarakhand",
    "tehri": "uttarakhand",
    "pauri": "uttarakhand",
    "chamoli": "uttarakhand",
    "uttarkashi": "uttarakhand",
    "rudraprayag": "uttarakhand",
    "valley of flowers": "uttarakhand",
    "nanda devi": "uttarakhand",
    "gangotri": "uttarakhand",
    "govind": "uttarakhand",
    "kedarnath": "uttarakhand",
    "askot": "uttarakhand",
    "binsar": "uttarakhand",
    "kolkata": "west bengal",
    "darjeeling": "west bengal",
    "jalpaiguri": "west bengal",
    "sundarbans": "west bengal",
    "siliguri": "west bengal",
    "howrah": "west bengal",
    "durgapur": "west bengal",
    "asansol": "west bengal",
    "midnapore": "west bengal",
    "medinipur": "west bengal",
    "bankura": "west bengal",
    "purulia": "west bengal",
    "malda": "west bengal",
    "murshidabad": "west bengal",
    "nadia": "west bengal",
    "north 24 parganas": "west bengal",
    "south 24 parganas": "west bengal",
    "hooghly": "west bengal",
    "cooch behar": "west bengal",
    "alipurduar": "west bengal",
    "jaldapara": "west bengal",
    "gorumara": "west bengal",
    "buxa": "west bengal",
    "neora valley": "west bengal",
    "singalila": "west bengal",
    "srinagar": "jammu and kashmir",
    "jammu": "jammu and kashmir",
    "anantnag": "jammu and kashmir",
    "baramulla": "jammu and kashmir",
    "kupwara": "jammu and kashmir",
    "pulwama": "jammu and kashmir",
    "udhampur": "jammu and kashmir",
    "kathua": "jammu and kashmir",
    "dachigam": "jammu and kashmir",
    "kishtwar": "jammu and kashmir",
    "hemis": "jammu and kashmir",
    "leh": "ladakh",
    "kargil": "ladakh",
    "changthang": "ladakh",
    "port blair": "andaman and nicobar islands",
    "puducherry": "puducherry",
    "pondicherry": "puducherry",
    "मुंबई": "maharashtra",
    "दिल्ली": "delhi",
    "बेंगलुरु": "karnataka",
    "कोलकाता": "west bengal",
    "चेन्नई": "tamil nadu",
    "हैदराबाद": "telangana",
    "लखनऊ": "uttar pradesh",
    "जयपुर": "rajasthan",
    "भोपाल": "madhya pradesh",
    "पटना": "bihar",
    "गुवाहाटी": "assam",
    "नागपुर": "maharashtra",
    "पुणे": "maharashtra",
    "कोल्हापुर": "maharashtra",
    "जगदलपुर": "chhattisgarh",
    "रायपुर": "chhattisgarh",
    "रांची": "jharkhand",
    "भुवनेश्वर": "odisha",
    "देहरादून": "uttarakhand",
    "शिमला": "himachal pradesh",
    "इंदौर": "madhya pradesh",
    "जबलपुर": "madhya pradesh",
    "अहमदाबाद": "gujarat",
    "सूरत": "gujarat",
    "चंडीगढ़": "chandigarh",
    "अमृतसर": "punjab",
    "श्रीनगर": "jammu and kashmir",
    "इम्फाल": "manipur",
    "कोहिमा": "nagaland",
    "अगरतला": "tripura",
    "शिलांग": "meghalaya",
    "गंगटोक": "sikkim",
    "वाराणसी": "uttar pradesh",
    "आगरा": "uttar pradesh",
    "कानपुर": "uttar pradesh",
    "नोएडा": "uttar pradesh",
    "ಬೆಂಗಳೂರು": "karnataka",
    "ಮೈಸೂರು": "karnataka",
    "ಮಂಗಳೂರು": "karnataka",
    "ಹುಬ್ಬಳ್ಳಿ": "karnataka",
    "ಬಳ್ಳಾರಿ": "karnataka",
    "ಶಿವಮೊಗ್ಗ": "karnataka",
    "ಬಂಡೀಪುರ": "karnataka",
    "ನಾಗರಹೊಳೆ": "karnataka",
    "ಧಾರವಾಡ": "karnataka",
    "ಬೆಳಗಾವಿ": "karnataka",
    "ಗುಲ್ಬರ್ಗ": "karnataka",
    "ಕೊಡಗು": "karnataka",
    "சென்னை": "tamil nadu",
    "கோயம்புத்தூர்": "tamil nadu",
    "மதுரை": "tamil nadu",
    "திருநெல்வேலி": "tamil nadu",
    "சேலம்": "tamil nadu",
    "హైదరాబాద్": "telangana",
    "విశాఖపట్నం": "andhra pradesh",
    "విజయవాడ": "andhra pradesh",
    "తిరుపతి": "andhra pradesh",
    "వరంగల్": "telangana",
    "কলকাতা": "west bengal",
    "দার্জিলিং": "west bengal",
    "শিলিগুড়ি": "west bengal",
    "കൊച്ചി": "kerala",
    "തിരുവനന്തപുരം": "kerala",
    "കോഴിക്കോട്": "kerala",
    "नागपूर": "maharashtra",
    "कोल्हापूर": "maharashtra",
    "चंद्रपूर": "maharashtra",
    "અમદાવાદ": "gujarat",
    "સુરત": "gujarat",
    "રાજકોટ": "gujarat",
    "ਅੰਮ੍ਰਿਤਸਰ": "punjab",
    "ਲੁਧਿਆਣਾ": "punjab",
    "ਚੰਡੀਗੜ੍ਹ": "chandigarh",
    "ਪੰਜਾਬ": "punjab",
    "ଭୁବନେଶ୍ୱର": "odisha",
    "କଟକ": "odisha",
}
